=== leticiarivlop/2021_LMSGI_DAS/2021_lmsgi_das/ud04/formularioHTML5/html5DAS.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/html5DAS.dtd

-->

<!--
    An example how to use this DTD from your XML document:

-->

<!--- Inicio del formulario -->
<!ELEMENT formulario (usuario|coche)*>

<!--- Definicion del usuario -->
<!ELEMENT usuario (nick|password)>
<!--- Nombre de usuario -->
<!ELEMENT nick (#PCDATA)>

<!--- Contraseña del usuario -->
<!ELEMENT password (#PCDATA)>

<!--- Informacion del coche -->
<!ELEMENT coche (marca|modelo|valor_num|informacion_prop|datos_vehiculo|localizacion_vehiculo)>

<!--- Marca del coche -->
<!ELEMENT marca (#PCDATA)>

<!--- Modelo del coche -->
<!ELEMENT modelo (#PCDATA)>

<!--- Valores numericos -->
<!ELEMENT valor_num (prec_min|prec_max|kilometros)>

<!--- Precio minimo del coche -->
<!ELEMENT prec_min (#PCDATA)>

<!--- Precio maximo del coche -->
<!ELEMENT prec_max (#PCDATA)>

<!--- Kilometros del coche -->
<!ELEMENT kilometros (#PCDATA)>

<!--- Informacion del propietario -->
<!ELEMENT informacion_prop (email|telefono|nombre)*>

<!--- Email del propietario -->
<!ELEMENT email (#PCDATA)>

<!--- Numero de telefono del propietario -->
<!ELEMENT telefono (#PCDATA)>

<!--- Nombre del propietario -->
<!ELEMENT nombre (#PCDATA)>

<!--- Datos del vehiculo -->
<!ELEMENT datos_vehiculo (descripcion|extras|fechaMatricula|fumador|color|imagen|semana_anuncio|paginasVenta)*>

<!--- Descripcion del vehiculo -->
<!ELEMENT descripcion (#PCDATA)>

<!--- Extras del vehiculo -->
<!ELEMENT extras (gps|asiento_calefactado|otrosExtras)*>

<!--- Marcar si el vehiculo tiene el extra GPS -->
<!ELEMENT gps (#PCDATA)>

<!--- Marcar si el vehiculo tiene el extra Asientos Calefactados -->
<!ELEMENT asiento_calefactado (#PCDATA)>

<!--- Escribir extras -->
<!ELEMENT otrosExtras (#PCDATA)>

<!--- Fecha de matriculacion -->
<!ELEMENT fechaMatricula (#PCDATA)>

<!--- Vehiculo de fumador -->
<!ELEMENT fumador (#PCDATA)>

<!--- Color del coche -->
<!ELEMENT color (#PCDATA)>

<!--- Imagen del coche. -->
<!ELEMENT imagen (#PCDATA)>

<!--- Semanas que durará el anuncio. -->
<!ELEMENT semana_anuncio (#PCDATA)>

<!--- Otras paginas donde tengas el coche a la venta. -->
<!ELEMENT paginasVenta (#PCDATA)>

<!--- Donde se encuentra el vehiculo. -->
<!ELEMENT localizacion_vehiculo (provincia)>

<!--- Provincia donde esta el vehiculo. -->
<!ELEMENT provincia (#PCDATA)>

=== leticiarivlop/2021_LMSGI_DAS/2021_lmsgi_das/ud04/formularioHTML5/html5DAS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE formulario SYSTEM "html5DAS.dtd">
<formulario
xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xsi:noNamespaceSchemaLocation='html5DAS.xsd'>
    <usuario>
        <nick>
            david A.
        </nick>
        <password>
            ********
        </password>
    </usuario>
    <coche>
        <marca>
            Renault 
        </marca>
        <modelo>
            Laguna
        </modelo>
        <valor_num>
            <prec_min>
                1500
            </prec_min>
            <prec_max>
                2000
            </prec_max>
            <kilometros>
                200000
            </kilometros>
        </valor_num>
        <informacion_prop>
            <email>
                david.apasir@educa.jcyl.es
            </email>
            <telefono>
                722289853
            </telefono>
            <nombre>
                David Aparicio
            </nombre>
        </informacion_prop>
        <datos_vehiculo>
            <descripcion>
                
            </descripcion>
            <extras>
                <gps>
                    si
                </gps>
                <asiento_calefactado>
                    Si
                </asiento_calefactado>
                <otrosExtras>
                    AC CC
                </otrosExtras>
            </extras>
            <fechaMatricula>
                02/02/2021
            </fechaMatricula>
            <fumador>
                No
            </fumador>
            <color>
                verde
            </color>
            <imagen>
                
            </imagen>
            <semana_anuncio>
                
            </semana_anuncio>
            <paginasVenta>
                milanunicios, wallapop
            </paginasVenta>
        </datos_vehiculo>
        <localizacion_vehiculo>
            <provincia>
                Zamora
            </provincia>
        </localizacion_vehiculo>
    </coche>
</formulario>
