=== leticiarivlop/2021_LMSGI_DAS/2021_lmsgi_das/ud06/04/04.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--- Elemento factura -->
<!ELEMENT factura (datos_emisor, datos_receptor,datos_factura)>
<!ATTLIST factura
    n_factura CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED
  >

<!--- Elemento datos_emisor -->
<!ELEMENT datos_emisor (nombre,dir,poblacion,provincia,cif,telefono?,fax?)>


<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ATTLIST poblacion
    cod_postal CDATA #IMPLIED
  >
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cif (#PCDATA)>

<!ATTLIST telefono
    num_tel CDATA #FIXED "917776688"  >

<!ELEMENT fax EMPTY>

<!ATTLIST fax
    num_fax CDATA #FIXED "917776688" >
<!--- Put your DTDDoc comment here. -->
<!ELEMENT datos_receptor (nombre,dir_env,poblacion,provincia)>
<!ATTLIST datos_receptor
    n_cli CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dir_env (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datos_factura (fecha,linea*,base,cuota_iva,total)>
<!ATTLIST datos_factura
    n_ped CDATA #IMPLIED
    iva CDATA #IMPLIED
    f_pago (efectivo|tarjeta|plazos) #REQUIRED
    moneda CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fecha (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT linea (ref,desc,cant,precio,importe)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ref (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT desc (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cant (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT precio (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT importe (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT base (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cuota_iva (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT total (#PCDATA)>

=== leticiarivlop/2021_LMSGI_DAS/2021_lmsgi_das/ud06/04/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE factura SYSTEM "04.dtd">
<factura n_factura="F555">        
    <datos_emisor>
        <nombre>Informática Sauces</nombre>
        <dir>Av. Federico Silva, 48</dir>
        <poblacion cod_postal="49800">Benavente</poblacion>
        <provincia>Zamora</provincia>
        <cif>Q-99777000</cif>
        <telefono/>
        <fax/>
    </datos_emisor>
    <datos_receptor n_cli="R879">
        <nombre>Victoria, Abril</nombre>
        <dir_env>Av. Gijón nº1 2ºd</dir_env>
        <poblacion cod_postal="28043">Madrid</poblacion>
        <provincia>Madrid</provincia>
    </datos_receptor>
    <datos_factura n_ped="E731" iva="16" f_pago= "efectivo" moneda="euro">
        <fecha>2005-12-01</fecha>
        <linea>
            <ref>MII93000F/8</ref>
            <desc>Intel</desc>
            <cant>1</cant>
            <precio>230</precio>
            <importe>266.80</importe>
        </linea>
        <linea>
            <ref>MB8QDIP4</ref>
            <desc>PLACA BASE QDI P4</desc>
            <cant>1</cant>
            <precio>180</precio>
            <importe>208.80</importe>
        </linea>
        <linea>
            <ref>MEDD512M32</ref>
            <desc>DIMM DDR 512MB 3200</desc>
            <cant>2</cant>
            <precio>40</precio>
            <importe>92.80</importe>
        </linea>
        <linea>
            <ref>HD250GSA7</ref>
            <desc>DISCO DURO 250GB S-ATA 7200</desc>
            <cant>4</cant>
            <precio>120</precio>
            <importe>556.80</importe>
        </linea>
        <base>970.00</base>
        <cuota_iva>155.20</cuota_iva>
        <total >1125.20</total>
    </datos_factura>
</factura>
